proxmox_url   = "https://pmoxchaac.imta.mx:8006/api2/json"
proxmox_node   = "pmoxchaac"
iso_file       = "local:iso/ubuntu-22.04.4-live-server-amd64.iso"
ssh_username   = "administrator"
storage        = "local"